[package]
name = "fluid_simulation"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.12.1"
rand="0.3.14"
rayon = "1.8.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
